# Semestrální projekt z NLA1 2024/25
**Zadání č. 3**<br>
**Kučera Ondřej**

## Úkol 1
Naprogramujte v programovacím jazyce Python LU rozklad matice $A\in \mathbb{R}^{n×n}, A = LU$,
pomocí následujícího pseudokódu:

$$
\begin{array}{l}
L = I; U = 0\\
\text{for } j = 1 : n\\
    \quad\begin{array}{l}
    \text{if } j = 1\\
        \quad\begin{array}{l}
        v(j : n) = A(j : n, j)
        \end{array}\\
    \text{else}\\
        \quad\begin{array}{l}
        \text{Solve } L(1 : (j - 1), 1 : (j - 1))z = A(1 : (j - 1), j) \text{ for } z\\
            \text{ and set } U(1 : (j - 1), j) = z\\
        v(j : n) = A(j : n, j) - L(j : n, 1 : (j - 1))z
        \end{array}\\
    \text{end if}\\
    \text{if } j < n\\
        \quad\begin{array}{l}
        L((j + 1) : n, j) = v((j + 1) : n) / v(j)
        \end{array}\\
    \text{end if}\\
    U(j, j) = v(j)
    \end{array}\\
\text{end for}
\end{array}
$$
    
Rozšiřte algoritmus tak, aby fungoval pro matice $A\in \mathbb{R}^{m×n}$, přičemž $m > n$, a zkuste odhadnout
potřebný počet operací ve tvaru $O(kn^l)$, resp. $O(\tilde{k}{m}^{\tilde{l}})$, tzn. parametry $k, l\in \mathbb{Q}$, resp. $\tilde{k}, \tilde{l}\in \mathbb{Q}$.

In [2]:
import numpy as np

In [45]:
def LU_rozklad(A):
    """
    Vypočítá LU rozklad čtvercové matice A.
    """
    m, n = A.shape
    if m != n:
        raise ValueError("Matice musí být čtvercová!")

    L = np.eye(n)
    U = np.zeros((n, n))
    v = np.zeros(n)

    for j in range(n):
        if j == 0:
            v[j:n] = A[j:n, j]
        else:
            z = np.zeros(j)
            for i in range(j):
                z[i] = (A[i, j] - L[i, 0:i] @ z[0:i]) / L[i, i]
            
            U[0:j, j] = z
            v[j:n] = A[j:n, j] - L[j:n, 0:j] @ z

        if j < n-1:
            L[j+1:n, j] = v[j+1:n] / v[j]
        
        U[j, j] = v[j]

    return L, U

In [68]:
A = np.array([[1, 1, 3],
              [2, 3, 5],
              [4, 4, 9]])

L, U = LU_rozklad(A)
print(L)
print(U)
print(np.allclose(A, L @ U))

[[1. 0. 0.]
 [2. 1. 0.]
 [4. 0. 1.]]
[[ 1.  1.  3.]
 [ 0.  1. -1.]
 [ 0.  0. -3.]]
True


In [87]:
def obecny_LU_rozklad(A):
    """
    Vypočítá LU rozklad obdélníkové matice A (m > n).
    """
    m, n = A.shape
    if m <= n:
        raise ValueError("Počet řádků matice musí být vyšší než počet sloupců!")

    L = np.eye(m)
    U = np.zeros((m, n))
    v = np.zeros(m)

    for j in range(n):
        if j == 0:
            v[j:m] = A[j:m, j]
        else:
            z = np.zeros(j)
            for i in range(j):
                z[i] = (A[i, j] - L[i, 0:i] @ z[0:i]) / L[i, i]
            
            U[0:j, j] = z
            v[j:m] = A[j:m, j] - L[j:m, 0:j] @ z

        if j < n-1:
            L[j+1:m, j] = v[j+1:m] / v[j]
        
        U[j, j] = v[j]
    
    for j in range(n, m):
        L[j, n-1] = (A[j, n-1] - L[j, 0:n-1] @ U[0:n-1, n-1]) / U[n-1, n-1]

    return L, U

In [88]:
A = np.array([[1, 2, -1, 0],
              [1, 4, 2, 4],
              [2, 6, 2, 2],
              [1, 4, 5, 3],
              [3, 8, 3, 3]])

L, U = obecny_LU_rozklad(A)
print(L)
print(U)
print(np.allclose(A, L @ U))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [2. 1. 1. 0. 0.]
 [1. 1. 3. 1. 0.]
 [3. 1. 3. 1. 1.]]
[[ 1.  2. -1.  0.]
 [ 0.  2.  3.  4.]
 [ 0.  0.  1. -2.]
 [ 0.  0.  0.  5.]
 [ 0.  0.  0.  0.]]
True


In [89]:
A = np.random.rand(10, 10)
L, U = LU_rozklad(A)
print(np.allclose(A, L@U))

A = np.random.rand(15, 10)
L, U = obecny_LU_rozklad(A)
print(np.allclose(A, L@U))

True
True
